server:
  port: 8764
  servlet:
    context-path: /consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka          # 访问注册中心（eureka）的基本路径
    register-with-eureka: true                          # 自身不需要向 eureka 注册
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30              # 服务失效时间，默认值是 90 秒，即某个服务超过 90 秒没有向 eureka-server 发送心跳，就会被认为宕机了，eureka-server 将其移出注册列表中
    lease-renewal-interval-in-seconds: 10                 # 服务续约（renewal）的间隔，默认 30 秒，即默认30秒 client 要向服务端发送一次心跳
  server:
    enable-self-preservation: true    # 开启 eureka 自我保护机制
    eviction-interval-timer-in-ms: 10000 # 扫描失效服务的间隔时间（缺省值：60*1000ms)
spring:
  application:
    name: consumer